import us.nebula.gradle.UploadBuildToServerTask
import us.nebula.gradle.Util

plugins {
    id 'com.github.gmazzo.buildconfig' version "$build_config_version"
    id 'application'
}

// Set to true when you want to build with all needed dependencies
// Defaulted to false because deps are placed on the server to launch w/ launcher
var BUILD_LOCAL = false
if (BUILD_LOCAL) {
    println "Local build is turned on, will not attempt to upload build"
}

var buildNumber = project.build_number
var gitHash = Util.execute("git rev-parse --short HEAD")
var gitBranch = Util.execute("git branch --show-current")

group = project.group
version = project.version

buildConfig {
    buildConfigField(String, "HASH", gitHash)
    buildConfigField(String, "BRANCH", gitBranch)
    buildConfigField(String, "VERSION", project.version)
    buildConfigField(String, "BUILD", buildNumber)
    buildConfigField(String, "BUILD_TIME", "${new Date(System.currentTimeMillis()).format("MM/dd/yyyy HH:mm")}")

    packageName "us.nebula"
    useJavaOutput()
    generateAtSync = true
}

application {
    mainClass = 'Start'
    applicationDefaultJvmArgs = Util.getLaunchJVMFlags()
}

run {
    workingDir = file(Util.createPathString(Util.USER_DIR, "run"))
    args += "-gameDir=$workingDir.absolutePath"
}

sourceSets.main.java.srcDirs += "build/gen/buildconfig/src/main"

configurations {
    jarLib
    implementation.extendsFrom(jarLib)
}

repositories {
    maven {
        name = "Minecraft Libraries"
        url = "https://libraries.minecraft.net/"
    }
}

var dependenciesPath = "dependencies$Util.SEPARATOR"
dependencies {
    implementation fileTree("${dependenciesPath}libraries")
    jarLib fileTree("${dependenciesPath}nebula_libraries")

    var lwjglVersion = Util.getOSType().is(Util.OS.OSX) ? mac_lwjgl_version : lwjgl_version
    implementation group: 'org.lwjgl.lwjgl', name: 'lwjgl', version: lwjglVersion
    implementation group: 'org.lwjgl.lwjgl', name: 'lwjgl_util', version: lwjglVersion
}

tasks.withType(Jar).configureEach {
    if (BUILD_LOCAL) {
        from {
            configurations.jarLib
                    .filter { !it.name.endsWithIgnoreCase(".sha256") }
                    .collect { it.isDirectory() ? it : zipTree(it) }
        }
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest.attributes(
            'Nebula-Version': project.version,
            'Nebula-BuildID': buildNumber,
            'Nebula-Branch': gitBranch,
            'Nebula-Hash': gitHash,
            'ImInYourWalls': 'true'
    )
}

tasks.withType(JavaCompile).configureEach {
    dependsOn(generateBuildConfig)
    if (!BUILD_LOCAL) {
        finalizedBy uploadBuildToServer
    }
}

tasks.register('uploadBuildToServer', UploadBuildToServerTask) {
    setGroup("nebula")
    setDescription("Creates a nebula build and uploads the build and its dependants to the server")

    setBuildDirectory(Util.createPathString(Util.USER_DIR, "build", "libs"))
    setLibrariesDirectory(Util.createPathString(Util.USER_DIR, "dependencies", "nebula_libraries"))
}