import us.nebula.gradle.Util
import us.nebula.gradle.task.GenerateBuildChecksumTask
import us.nebula.gradle.task.GenerateLibraryChecksumTask
import us.nebula.gradle.task.PublishBuildDataTask

plugins {
    id 'com.github.gmazzo.buildconfig' version "$build_config_version"
    id 'application'
}

var buildNumber = project.build_number
var gitHash = Util.execute("git rev-parse --short HEAD")
var gitBranch = Util.execute("git branch --show-current")
var directory = Util.createPathString(Util.USER_DIR, "")

group = project.group
version = project.version
archivesBaseName = "nebula+$buildNumber-${gitBranch}_$gitHash"

buildConfig {
    buildConfigField(String, "HASH", gitHash)
    buildConfigField(String, "BRANCH", gitBranch)
    buildConfigField(String, "VERSION", project.version)
    buildConfigField(String, "BUILD", buildNumber)
    buildConfigField(String, "BUILD_TIME", "${new Date(System.currentTimeMillis()).format("MM/dd/yyyy HH:mm")}")

    packageName "us.nebula"
    useJavaOutput()
    generateAtSync = true
}

application {
    mainClass = 'Start'
    applicationDefaultJvmArgs = Util.getLaunchJVMFlags()
}

run {
    workingDir = file("${directory}run")
    args += "-gameDir=$workingDir.absolutePath"
}

sourceSets.main.java.srcDirs += "build/gen/buildconfig/src/main"

configurations {
    library
}

repositories {
    mavenCentral()
    maven {
        name = 'Velocity Repository'
        url = 'https://nexus.velocitypowered.com/repository/maven-public/'
    }
}

var dependenciesPath = "dependencies$Util.SEPARATOR"
dependencies {
    library group: 'net.java.dev.jna', name: 'jna', version: jna_version
    library fileTree("${dependenciesPath}buildLibraries")
    // multi-os support!!
    implementation fileTree("${dependenciesPath}shared")
    implementation configurations.library

    // why is this such a pain in my dick to do...
    // using 2.9.4 on MacOS crashes real nice...
    // for whatever reason, the repos do not have the 2.9.1 version either so... manually add them i guess
    if (Util.getOSType() == Util.OS.MAC) {
        implementation fileTree("${dependenciesPath}macos${Util.SEPARATOR}libraries")
    } else {
        implementation group: 'org.lwjgl.lwjgl', name: 'lwjgl', version: lwjgl_version
        implementation group: 'org.lwjgl.lwjgl', name: 'lwjgl-platform', version: lwjgl_version, ext: 'pom'
        implementation group: 'org.lwjgl.lwjgl', name: 'lwjgl_util', version: lwjgl_version
    }
}

tasks.withType(Jar).configureEach {
    from {
        configurations.library.collect {
            if (it.name.endsWithIgnoreCase(".sha256")) {
                return
            }
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest.attributes(
            'Nebula-Version': project.version,
            'Nebula-BuildID': buildNumber,
            'Nebula-Branch': gitBranch,
            'Nebula-Hash': gitHash,
            'ImInYourWalls': 'true'
    )
}

tasks.withType(JavaCompile).configureEach {
    dependsOn(generateBuildConfig)
}

tasks.register('publishBuildData', PublishBuildDataTask) {
    setGroup("nebula")
    setDescription("Publishes build data to a GitHub Gist")

    setDirectory(directory)
    setGitHash(gitHash)
    setBuildID(buildNumber)
    setVersion(project.version)
}

tasks.register('generateBuildChecksum', GenerateBuildChecksumTask) {
    setGroup("nebula")
    setDescription("Creates a checksum file for the build")

    setBuildDirectory("${directory}build${Util.SEPARATOR}libs")
}

tasks.register('generateLibraryChecksums', GenerateLibraryChecksumTask) {
    setGroup("nebula")
    setDescription("Creates *.sha256 files with each files checksum for the Nebula launcher")

    setDirectory("${dependenciesPath}buildLibraries")
}

tasks.register('createNebulaBuild') {
    setGroup("nebula")
    setDescription("Runs the normal 'build' task with both publishBuildData and generateLibraryChecksums tasks")

    dependsOn(build)
    dependsOn(publishBuildData)
    dependsOn(generateLibraryChecksums)
    dependsOn(generateBuildChecksum)
}