group=nebula.client
version=4.0.0
build_number=1

# versions
build_config_version=5.3.5
vecmath_version=1.5.2
websocket_version=1.5.3
jna_version=5.16.0

# mc shit
log4j_version=2.24.3
commons_lang3_version=3.1
lwjgl_version=2.9.4-nightly-20150209
lwjgl_version_mac=2.9.1-nightly-20131017
trove4j_version=3.0.3
jopt_simple_version=4.5
netty_version=4.0.10.Final
commons_io_version=2.4
gson_version=2.2.4